config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end
  
  resources :apps do
    collection do
      get 'myapps'
      get 'demoapps'
    end
  end

  devise_for :users
  
  get 'home/contact'
  root 'home#about'
end

app/models/app.rb
class App < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy
  
  validates :name, presence: { message: 'Application name cannot be emptied.' }
  validates :url, presence: { message: 'Application url cannot be emptied.' }
  validates :user, presence: { message: 'An application must have associated user.' }
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :app
  
  validates :name, presence: { message: 'Event name cannot be emptied.' }
  validates :app, presence: { message: 'An event must have associated application.' }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :apps         
  before_save { self.email = email.downcase if email.present? }
  after_initialize :init
  
  validates :password, length: { minimum: 6 }, allow_blank: true
  validates :email,
             presence: true,
             uniqueness: { case_sensitive: false },
             length: { minimum: 3, maximum: 254 }
         
  def init
    self.role  ||= :standard           
  end
  
  enum role: [:standard, :admin]         
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    registered_application = App.find_by(url: request.env['HTTP_ORIGIN'])
    
    if registered_application.nil?
      render json: "Unregistered application", status: :unprocessable_entity
    else
      @event = registered_application.events.build(event_params)  
        if @event.save
          render json: @event, status: :created
        else
          render json: {errors: @event.errors}, status: :unprocessable_entity
        end
    end
  end
  
  def preflight
    head 200
  end
  
  private
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :role, :password, :password_confirmation, :current_password) }
  end
  
  def error_messages(records)
    err = "Error! "
    records.errors.each do |attribute, message|
      err = err + " " + message 
    end
    return err
  end

end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  def index
    @apps = App.all
  end

  def show
    @app = App.find(params[:id])
    @events = @app.events(:group => 'name')
  end

  def new
    @app = App.new
  end  
  
  def create
    @app = App.new(app_params)

    if @app.save
      redirect_to @app, notice: "Application was registered successfully."
    else
      flash.now[:alert] = error_messages(@app)
      render :new
    end
  end
  
  def edit
    @app = App.find(params[:id])
  end
  
  def update
    @app = App.find(params[:id])
    
    if app_owner?
      @app.assign_attributes(app_params)
      if @app.save
        redirect_to @app, notice: "Application was updated successfully."
      else
        flash.now[:alert] = error_messages(@app)
        render :edit
      end
    else
      flash[:notice] = "Unauthorized: not an application owner."
      redirect_to @app
    end
  end
  
  def destroy
    @app = App.find(params[:id])
    
    if app_owner?
      if @app.destroy
        flash[:notice] = "\"#{@app.name}\" was deleted successfully."
        redirect_to myapps_apps_path
      else
        flash.now[:alert] = "There was an error deleting the application."
        render :show
      end
    else
      flash[:notice] = "Unauthorized: not an application owner."
      redirect_to @app
    end
  end
  
  def myapps
    @apps = App.where(user_id: current_user.id).order('created_at desc')
  end

  def demoapps
    @apps = App.where(user_id: 1).order('created_at desc')
    # assuming db is seeded with admin
  end

  private
  def app_params
    params.require(:app).permit(:name, :url, :user_id)
  end
  
  def app_owner?
    @app.user.id == current_user.id || current_user.admin?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def app_owner?
    user_signed_in? && @app.user_id == current_user.id
  end
  
  def event_owner?
    user_signed_in? && @event.app.user_id == current_user.id
  end
  
  def admin?
    user_signed_in? && current_user.admin?
  end
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/apps/_form.html.erb
<%= form_for app do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control', placeholder: "Enter application url" %>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.submit "Save", class: 'btn btn-success' %>
  <%= link_to "Cancel", cancel_link, class: 'btn btn-default' %>
<% end %>

app/views/apps/_guideline.html.erb
<p>Guidelines for application:</p>
<ul>
  <li>Make sure the title is appropriate.</li>
  <li>Never insult dogs or cats.</li>
  <li>Smile when you type.</li>
</ul>

app/views/apps/demoapps.html.erb
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-10 top">
    <h4>Demo Applications</h4>
  </div>
  <div class="col-md-1">
  </div>
</div>
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-10 mid">
    <p class="text-info"><small>
      <%= pluralize(@apps.count, "demo application") %> by admin<br />
    </small></p>  
    <% @apps.each do |app| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading"><%= link_to app.name, app %> - <%= app.url %></h4>
          <small class="text-info">created <%= time_ago_in_words(app.created_at) %> ago
          <p><%= pluralize(app.events.count, "event") %></p></small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-1">
  </div>
</div>

app/views/apps/edit.html.erb
<div class="row">
  <div class="col-md-4">
  </div>
  <div class="col-md-4 entry edit-app">
    <h4>Edit Registered Application</h4>
    <%= render partial: 'guideline' %>
    <%= render partial: 'form', locals: { app: @app, cancel_link: @app } %>
  </div>
    <div class="col-md-4">
  </div>
</div>

app/views/apps/index.html.erb
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-10 top">
    <h4>All Applications</h4>
  </div>
  <div class="col-md-1">
  </div>
</div>
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-10 mid">
    <% @apps.each do |app| %>
     <div class="media">
        <div class="media-body">
          <h4 class="media-heading"><%= link_to app.name, app %> - <%= app.url %></h4>
          <p><small class="text-info"><%= pluralize(app.events.count, "event") %>, owner - <%= app.user.email %></small></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-1">
  </div>
</div>

app/views/apps/myapps.html.erb
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-10 top">
    <h4>My Registered Applications</h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
     <%= link_to "New Application", new_app_path, class: 'btn btn-primary' %>
  </div>
  <div class="col-md-1">
  </div>
</div>
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-10 mid">
    <p class="text-info"><small>
      <%= pluralize(@apps.count, "application") %> by <%= current_user.email %><br />
    </small></p>  
    <% @apps.each do |app| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading"><%= link_to app.name, app %> - <%= app.url %></h4>
          <small class="text-info">created <%= time_ago_in_words(app.created_at) %> ago
          <p><%= pluralize(app.events.count, "event") %></p></small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-1">
  </div>
</div>

app/views/apps/new.html.erb
<div class="row">
  <div class="col-md-4">
  </div>
  <div class="col-md-4 entry edit-app">
    <h4>Register New Application</h4>
    <%= render partial: 'guideline' %>
    <%= render partial: 'form', locals: { app: @app, cancel_link: myapps_apps_path } %>
  </div>
  <div class="col-md-4">
  </div>
</div>

app/views/apps/show.html.erb
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-10 top">
    <h4><%= @app.name %></h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <% if app_owner? || admin? %> 
      <%= link_to "Edit Application", edit_app_path, class: 'btn btn-primary' %>
      <%= link_to "Delete Application", @app, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this application?' } %>
    <% end %>
  </div>
  <div class="col-md-1">
  </div>
</div>
<div class="row"> 
  <div class="col-md-1">
  </div>
  <div class="col-md-10 mid">
    <div class="row"> 
      <div class="col-md-4">
        <p><%= link_to @app.url, "#{@app.url}", :target => '_blank' %>
        <br /><br />
        <% @events.group_by(&:name).each do |name, events| %>
          <div class="media">
            <div class="media-body">
              <h4 class="media-heading">
                <%= name %><small>  - count: <%= events.count %></small>
              </h4>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-md-6">
        <% if @app.events.count != 0 %>
          <%= pie_chart @events.group(:name).count, width: "600px", height: "250px" %>
          <br />
          <%= line_chart @events.group_by_day(:created_at).count, xtitle: "Time", ytitle: "Events", width: "600px", height: "250px" %>
        <% else %>
          <br /><br /><small>**  no events  **</small>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-1">
  </div>
</div>

app/views/home/about.html.erb
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-10 mid cover">
    <div>
      <h3>Welcome to Metrics</h3>
      <h4>An API tracking service and reporting tool</h4><br />
      <%= image_tag("pie-chart.png", size: "350x300", alt: "pie chart") %>
    </div>
    <div class="row sell-bottom">
      <div class="col-md-4">
        <i class="glyphicon glyphicon-eye-open gz"></i>
        <h4>Monitor</h4>
        <p>Allows users to track events on their website.</p>
      </div>
      <div class="col-md-4">
        <i class="glyphicon glyphicon-equalizer gz"></i>
        <h4>Record</h4>
        <p>Provides server-side API that saves those events to database.</p>
      </div>
      <div class="col-md-4">
        <i class="glyphicon glyphicon-scale gz"></i>
        <h4>Report</h4>
        <p>Displays captured metrics for data analysis.</p>
      </div>
    </div>
  </div>
  <div class="col-md-1">
  </div>
</div>

app/views/home/contact.html.erb
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-10 mid cover">
    <br /><br />
    <h4>Contact</h4>
    <p>Questions or comments please contact tmoolmuang@gmail.com</p>
  </div>
  <div class="col-md-1">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Metrics</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li>
          <%= link_to root_path do %>
            <i class="glyphicon glyphicon-home"></i>&nbsp;&nbsp;Home
          <% end %>
        </li>
        <% if !admin? %>
          <li>
            <%= link_to demoapps_apps_path do %>
              <i class="glyphicon glyphicon-stats"></i>&nbsp;&nbsp;Demo Applications
            <% end %>
          </li>
        <% end %>
        <% if user_signed_in? %>
          <li>
            <%= link_to myapps_apps_path do %>
              <i class="glyphicon glyphicon-star"></i>&nbsp;&nbsp;My Applications
            <% end %>
          </li>
          <% if admin? %>
            <li>
              <%= link_to apps_path do %>
                <i class="glyphicon glyphicon-cog"></i>&nbsp;&nbsp;All Applications
              <% end %>
            </li>
          <% end %>
        <% end %>
        <li>
          <%= link_to home_contact_path do %>
            <i class="glyphicon glyphicon-envelope"></i>&nbsp;&nbsp;Contact
          <% end %>
        </li>
        <div class="navbar-right user-info">
        <% if user_signed_in? %>
          <strong class="twitter-blue"><%= current_user.email %></strong> |
          <%= link_to edit_user_registration_path do %>
	          <i class="glyphicon glyphicon-user"></i>&nbsp;&nbsp;Edit profile
          <% end %> - 
          <%= link_to destroy_user_session_path, method: :delete do %>
	          <i class="glyphicon glyphicon-log-out"></i>&nbsp;&nbsp;Sign Out
          <% end %>
        <% else %>
          <%= link_to new_user_registration_path do %>
	          <i class="glyphicon glyphicon-pencil"></i>&nbsp;&nbsp;Sign Up
          <% end %> -
          <%= link_to new_user_session_path do %>
	          <i class="glyphicon glyphicon-log-in"></i>&nbsp;&nbsp;Sign In
          <% end %>
        <% end %>
       </div>
      </ul>
      <div class="row">
        <div class="col-md-4"> 
        </div>
        <div class="col-md-4"> 
        <% if flash[:notice] %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
        <% elsif flash[:alert] %>
          <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
        <% end %>
        </div>
        <div class="col-md-4"> 
        </div>
      </div>
    </div>
    
    <%= yield %>
  
  </body>
</html>